package com.scaleguard.server.licencing.licensing;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

public class LicenceGenerator {

    public static void main(String[] args) throws InvalidAlgorithmParameterException, NoSuchPaddingException, IllegalBlockSizeException, NoSuchAlgorithmException, IOException, InvalidKeySpecException, BadPaddingException, InvalidKeyException {
       String gen= LicenceServer.generateLicence(
               "eyJrZXkiOiJ2dGFhd3N2bXdTYzFETHJDYTV6NlQ4NTBlbGZFOFNoN09TK0lIcTd0Z2RMSHNOWlplc3d1TERZWjQrYmhWWVE5WjJtR2ZYbklGZ29IemdHai9FdGlzak1pVVV2Q28zMldKUFFZM2g4UmQ5SE5mNWVOb1ZmMjlEeW9GaFhFS0s1NGxHckl3Vmp4THpOdDlRTmtpY1pIeU5zYjJvVHI2ZDdFVENNNnU4VWNnZ2JwUW00Y0hOSkoxNmpIMGNUc3VLZzV3dWZ5eXdCaDE5UUdrLzBmZVRzclhjWFduN0VURmpSQjNJM3YweXQ5MzI2NzhQRU4xREh2N08wNitVV2dqQVo4V0NoOVoyTzJlR2ZMQWVqRmk4QUpGVEhrcllQNXo4L0hFZTd1R1pjc0ZDYWdwMkpwNzk4WTdXR0lBRzFURDI0QzdNNzAzdmlNMlB1ZWdVa3NpQkpVUjJZdndseWp3NUMyd1hubHdMeGFWaURxQmJHTFlkdldXejM1MSsra0dkUDk5Tk93dytEeHp2V0svVk9tYWhWbEh6ZkFGaUc4d0ppd0JmbFBMZDgwakxtSVlRWUtzS3RNQmM0ektYMDF6RVI0VkxZeVpTY3dOUzVIelQwUXFxVEFpY3NOeVNUbzE4Uy9uejJIQUZjVUVUT1UyUHFWZnN1eHBLMmwzdGxnbGVSZlFyazJ3MytKTEJXNjJIVzdacFJtbXJIUGVzVlkwRzkrY0NlQkU0UHhYVEx0WHJkcUNJeVlTaHlldk82N3lxWVM1ZzE1aXBYbEFSM2xmL2NIaTdsS1lxMVprRm5raS84RzRZNlJYc3lWVjgzRUZXbnEzMFhRT1Brd0pRRmJaR09paDExaWVoMk1MdWdwYVVMR2VwQTFOaG9IQ0pybGVHaE5kYS9zdTZqaHlVVT0iLCJwYXlsb2FkIjoiSnEwSmd6c24yTTJvRXV2V04zUW5KSXVDUzk5d1ZFQmVESmJGQVl4N0RVNWlndmY2YTlJcGdwQUJjQmMySG9yWFphZ0JzU3FPdWRkVzlpR1BtZllOSlBES01FeHhGa3ZLUjNCYmN0OUpNQlB6THl0Y0lCYWNKdWR0RnpYMjNmWHR3dTJxZTFGQm1RTE8vUmRPeElJWGJLb3prN2d4bmhMM0ZaZldzYjkvZkovYUdDR3NPeW9OUlBLQ2sxUjVya1BMemdHNFBwZEJLSGhBb2NkbzlZNkphK0ZsQmJTQnZJU2ltZSttdkV6MjdLT0tYc0dQZDJwVml6cmIvNUtmUW9CNWUweDhJM0tHWWhCYlBMUFVHeWZYeFM0cEtEVlZpaVdJU044LzJyWmFyaDdLbStaSVh4OG5PYnRDUWtzcTVqa3BMKzR0NlVOWGdPNE51K1JxS3V3bW5nPT0ifQ=="
       ,300);
        System.out.println(gen);
        new FileOutputStream("licence_generated.key").write(gen.getBytes());
    }
}
