package com.scaleguard.server.licencing.licensing;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import java.io.IOException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

public class LicenceActivator {

    public static void main(String[] args) throws InvalidAlgorithmParameterException, NoSuchPaddingException, IllegalBlockSizeException, NoSuchAlgorithmException, IOException, InvalidKeySpecException, BadPaddingException, InvalidKeyException {

        try {
            System.out.println(LicenceManager.activateLicence("{\"payload\":\"eyJrZXkiOiJZaTM5R0hEZFRkWGpjd1ZoSVFiS284SDJPWk1tdGRWMjFhdk9KajMvbmdxeEUvVXhuWWhNdXRaa0JtREtGRzZEaUg1Z094M2c3Rmo5MzZJUmVZTjN2eEJmbFJ3dndqVEd0d2tsdVdpUFhLYWkrY3ltL3BMNGhuam9GYURsNHNQR3Fjc1RqdGcraHZjK1NrT01FeW0vdEgxdmtPM2FTNHczSDMxNjZJVUZHNkVZVHV4UVZ1SHhPd2Y1WktOSXVsUFh1WUxYa0dYaGpNcTlKYlJGeS9hK2pDeHBPekJXTld4WW1IK3dweStHNXlmS2R1b0ExZFR3dFE2SWVRU2FhL0x3cG9uUmR6dWtaRlVFQ0tBVFFlMjd1ZGFpdG5raHVHTjc1djY0RzNKbGJ6aCtobjIrNWlDL2FXV3FDcXdsZHhrdndBajczRHQrTk91cnNwSTBUSEFEZWk5SUg4NlRPUGJhRmtLMVFtTm5FbWNBb2Q1ZUF0UjNFeTBYb3FFOU1IQ3FlVmN6dnVJN0x2N3E3S3krMjFxQ3FCdEZQQngvMDFua3pXcEtJSVJYR1hkOGlsZmI4Y3BJSmpuVFM5ZUdpbE5ld3F2aGk3dkduRWRtVkxVLzY4VUg1Vi9OQ0RndUdDWEFJamhmZVl2MGxTVnovVEVORWNSM01GZmxMdjRVZVp3VWg1aEdXQVp0RXdjc01PSDFoZms0OVRwYmpOQ1lPVW1IcDlsWFJBcTR4SHFmaEtFMU04RDdrWGloeXlwaEZFZ1FCQTRYOEZvU3V5SmtlWUdnSmVGejZEK0tVRmVqNTVMTkRvbVFBRU1LOXdDWm44Y2dLU0s3aFpBSllMZG84YytBdWVOME0wS01WcXIyNkIvSnZwN1UrRlVFUFkzYUVBdlFISVRBQm1JL1hhMD0iLCJwYXlsb2FkIjoic0tyWEpsSzNRUmZOcHFINzB6cUY2RkZkbG82am5pQlBuNXNoOWkxdFU3V2JaNEtkRkxvdTVwWWhNUitBb3NoT1ZjZnNnQ1hIa0QxcXBBa0g0QkdHazJQcDZjREcyQTU2RzJUeHFxaE1tSDJjWVpIR3NDclhxV1VDeUdGSGh5OXVVMDBOdk5qeWtsRjZFZ2Z1STluSjV0dDNvQjBiU1oxUUwxMVcvSzVKSjVhaWpGaFlyWUZWWlJPMitZaTdwNGt1aGIxRDh1REpiUjJXTU9ybWd0Y0cyc2w1cDNnWXFoQldlVk1QM09RYnltVmYyREtoMnRkK3RVa3ppZWlYa3ZCT3V6aXdBUWFkTVh0U3hQTUNXNkdNQUFaTlAzYXNBa3pLVGhOU2JnZVAxUytVaXMxTTVrby9ianQ2a1dCdTVwSHI3MlU4OXFXV3VXLzNRTHpwMk1MRHo0MUtoWlN4a2xSZnlPN21UaXQrR0dqbzAzb044dkVjMVVGUG5TREdJU1czIn0=\",\"passcode\":\"Karthik123$\"}"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
